### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by gbraad** [vrutkovs/firefox-flatpak#3]
Currently I am setting up an automated build at GitLab: https://gitlab.com/gbraad/flatpak-firefox

at the moment not sure if it is completely functional yet, but just let me know if you think this is something to be included?

**Comment by vrutkovs** [comment]
I think its pretty functional (I use it from time to time), although I think it would be a good idea to play with config parameters. I tried to stay as close as possible to the ones Fedora is using, but that might not be the ideal set

**Comment by gbraad** [comment]
I meant 'functional' about my own automated build... Sorry... it eventually failed due to a repo issue.
But i will certainly help out with improving this a bit. I actually built it know with a docker container I made a while back: https://gitlab.com/gbraad/flatpak-builder-gnome and i have another one for the freedesktop stuff. If you have suggestion about this, please let me know

**Comment by vrutkovs** [comment]
Oh, awesome. I've built this last time about two weeks ago and it worked. Probably flatpak is now more strict about this.

Lets move to https://gitlab.com/gbraad/flatpak-firefox/issues/1 - I'll backport the changes here as well
