### ISSUE TITLE
Firefox won't start at all on Xorg after update

### ISSUE THREAD

**Issue by Saroufim** [vrutkovs/firefox-flatpak#8]
Firefox would now just segfault on Xorg after today's update. It works just fine on Wayland though.

**Comment by stransky** [comment]
I think Jan hardcoded the wayland backend here, 

GDK_BACKEND=x11 flatpak run org.mozilla.FirefoxNightly -no-remote

run on wayland although it should use x11 backend.

**Comment by vrutkovs** [comment]
All these issues should go to xhorak's fork anyway
